steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-100946316/app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-100946316/app:$COMMIT_SHA']

images:
  - 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-100946316/app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
